import { describe, it, expect, beforeAll } from 'vitest';
import { MessengerClient } from './messenger.js';
import {
    generateEG,
    computeDH,
    decryptWithGCM,
    generateECDSA,
    signWithECDSA,
    HMACtoAESKey,
    bufferToString,
    govEncryptionDataStr,
    fromBase64
} from './lib.js';

const stringifyCert = function (cert) {
    if (typeof cert === 'object') {
        return JSON.stringify(cert);
    } else if (typeof cert === 'string') {
        return cert;
    } else {
        throw new Error('Certificate is not a JSON or string');
    }
}

// Decrypt a message using the government secret key
const govDecrypt = async function (secret, [headerStr, ct]) {
    const header = JSON.parse(headerStr);
    const { subtle } = window.crypto;

    // headers MUST have the field "vGov"!!!
    // Import vGov (JWK) back to CryptoKey
    const vGovKey = await subtle.importKey(
        'jwk',
        header.vGov,
        { name: 'ECDH', namedCurve: 'P-384' },
        true,
        []
    );

    let govKey = await computeDH(secret, vGovKey);
    govKey = await HMACtoAESKey(govKey, govEncryptionDataStr);

    // headers MUST have the field "cGov" and "ivGov"!!!
    const cGov = fromBase64(header.cGov);
    const ivGov = fromBase64(header.ivGov);
    const receiverIV = fromBase64(header.receiverIV);

    // note that the next line does not have a custom authenticatedData field set
    const mkRaw = await decryptWithGCM(govKey, cGov, ivGov);

    // Import the decrypted MK
    const subtleMK = await subtle.importKey('raw', mkRaw, 'AES-GCM', true, ['encrypt', 'decrypt']);

    const plaintext = await decryptWithGCM(subtleMK, ct, receiverIV, headerStr);
    return bufferToString(plaintext);
}

describe('Messenger', function () {
    // Vitest timeout is configurable, default 5000ms is usually fine, but crypto can be slow
    // this.timeout(5000) 

    describe('functionality', function () {
        let caKeyPair
        let govKeyPair

        beforeAll(async function () {
            // Key pair for the certificate certAuthority which will sign all certificates
            // generated by clients before relaying them to other clients
            caKeyPair = await generateECDSA()
            // keypair for the government to be able to decrypt all messages
            govKeyPair = await generateEG()
        })

        it('imports a certificate without an error', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
        })

        it('generates an encrypted message without error', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await alice.sendMessage('bob', 'Hello, Bob')
        })

        it('bob can recieve an encrypted message from alice', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const aliceCertificate = await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await bob.receiveCertificate(aliceCertificate, aliceCertSignature)
            const message = 'Hello, Bob'
            const ct = await alice.sendMessage('bob', message)
            const result = await bob.receiveMessage('alice', ct)
            expect(result).toEqual(message)
        })

        it('cannot find identical messages with identical ciphertexts', async function () {
            try {
                const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
                const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
                const aliceCertificate = await alice.generateCertificate('alice')
                const bobCertificate = await bob.generateCertificate('bob')
                const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
                const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
                await alice.receiveCertificate(bobCertificate, bobCertSignature)
                await bob.receiveCertificate(aliceCertificate, aliceCertSignature)
                const message = 'Hello, Bob'
                const ct1 = await alice.sendMessage('bob', message)
                const ct2 = await alice.sendMessage('bob', message)
                expect(JSON.stringify(ct1)).not.toEqual(JSON.stringify(ct2))
            } catch {
                // If no ciphertexts are generated because an exception is thrown,
                // then we can't find two identical messages with identical ciphertexts
            }
        })

        it('cannot find ciphertext that contains plaintext', async function () {
            try {
                const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
                const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
                const aliceCertificate = await alice.generateCertificate('alice')
                const bobCertificate = await bob.generateCertificate('bob')
                const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
                const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
                await alice.receiveCertificate(bobCertificate, bobCertSignature)
                await bob.receiveCertificate(aliceCertificate, aliceCertSignature)
                const message = 'Hello, Bob'
                const ct1 = await alice.sendMessage('bob', message)
                expect(JSON.stringify(ct1)).not.include(message)
            } catch {
                // If no ciphertexts were generated, then we can't find any ciphertexts
                // that include copy of the plaintext
            }
        })

        it('alice and bob can have a conversation', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const aliceCertificate = await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await bob.receiveCertificate(aliceCertificate, aliceCertSignature)
            let message = 'Hello, Bob'
            let ct = await alice.sendMessage('bob', message)
            let result = await bob.receiveMessage('alice', ct)
            expect(result).toEqual(message)
            message = 'Hello, Alice'
            ct = await bob.sendMessage('alice', message)
            result = await alice.receiveMessage('bob', ct)
            expect(result).toEqual(message)
            message = 'Meet for lunch?'
            ct = await bob.sendMessage('alice', message)
            result = await alice.receiveMessage('bob', ct)
            expect(result).toEqual(message)
        })

        it('the government can decrypt an encrypted message from alice', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const aliceCertificate = await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await bob.receiveCertificate(aliceCertificate, aliceCertSignature)
            const message = 'Hello, Bob'
            const ct = await alice.sendMessage('bob', message)
            const result = await govDecrypt(govKeyPair.sec, ct)
            expect(result).toEqual(message)
        })

        // // EXTENDED TEST CASES

        it('certificates with invalid signatures are rejected', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bobCertificate = await bob.generateCertificate('bob')
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            const invalidSignature = await signWithECDSA(caKeyPair.sec, 'fake_signature')

            // Vitest equivalent of expect(...).to.not.be.rejected is just ensuring it awaits successfully
            // or explicit .resolves.not.toThrow()
            await expect(alice.receiveCertificate(bobCertificate, bobCertSignature)).resolves.not.toThrow()

            await expect(alice.receiveCertificate(bobCertificate, invalidSignature)).rejects.toThrow()
        })

        it('message replay attacks are detected', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const aliceCertificate = await alice.generateCertificate('alice')
            const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
            const bobCertificate = await bob.generateCertificate('bob')
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await bob.receiveCertificate(aliceCertificate, aliceCertSignature)
            const message = 'Hello, Bob'
            const ct = await alice.sendMessage('bob', message)
            await bob.receiveMessage('alice', ct)

            await expect(bob.receiveMessage('alice', ct)).rejects.toThrow()
        })

        it('alice rejects messages where she is not intended recipient', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const claire = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            const claireCertificate = await claire.generateCertificate('claire')
            const claireCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(claireCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await alice.receiveCertificate(claireCertificate, claireCertSignature)
            await bob.receiveCertificate(claireCertificate, claireCertSignature)
            const message = 'Hello, Claire'
            const ct = await bob.sendMessage('claire', message)

            await expect(alice.receiveMessage('claire', ct)).rejects.toThrow()
        })

        it('can encrypt and decrypt a file successfully', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const aliceCertificate = await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await bob.receiveCertificate(aliceCertificate, aliceCertSignature)

            // Mock a file (Blob/File not fully supported in pure jsdom same as browser, but ArrayBuffer is)
            const fileContent = new Uint8Array([1, 2, 3, 4, 5]);
            const fileCheck = new Uint8Array([1, 2, 3, 4, 5]);
            // We need to use the lib's encryptFile/decryptFile, but they are not exported by MessengerClient
            // They are standalone functions in lib.js. 
            // However, typically a messenger integration would involve:
            // 1. Messenger encrypts file key with sendMessage
            // 2. File itself is encrypted with encryptFile

            // Let's import them from lib.js (I need to update imports first)
            // But wait, the user wants "test tất cả chức năng". Code for file handling is in `lib.js` but `messenger.js` doesn't use it directly?
            // `messenger.js` sends text. The UI likely calls `encryptFile`, sends the `key` via `messenger.sendMessage`, and uploads the blob.

            // So we simulate that flow:
            const { encryptFile, decryptFile } = await import('./lib.js');

            // mock File object
            const file = new File([fileContent], "test.txt", { type: "text/plain" });

            const { encryptedBlob, key, iv, type } = await encryptFile(file);

            // Alice sends the key to Bob securely
            // The key is raw bytes (ArrayBuffer). Messenger sends strings.
            // We must encode the key to string (Base64) to send via messenger.
            const keyStr = btoa(String.fromCharCode(...new Uint8Array(key)));
            const ivStr = btoa(String.fromCharCode(...new Uint8Array(iv)));
            const msgPayload = JSON.stringify({ key: keyStr, iv: ivStr, type });

            const ct = await alice.sendMessage('bob', msgPayload);
            const receivedPayloadStr = await bob.receiveMessage('alice', ct);
            const receivedPayload = JSON.parse(receivedPayloadStr);

            // Verify Government can ALSO see the file key!
            const govDecryptedPayloadStr = await govDecrypt(govKeyPair.sec, ct);
            expect(govDecryptedPayloadStr).toEqual(msgPayload);

            // Bob decrypts file
            const receivedKey = new Uint8Array(atob(receivedPayload.key).split('').map(c => c.charCodeAt(0)));
            const receivedIv = new Uint8Array(atob(receivedPayload.iv).split('').map(c => c.charCodeAt(0)));

            // In real app, encryptedBlob is sent via server. Bob has it.
            // We need to convert Blob back to ArrayBuffer for decryptFile in test (or pass Blob if supported)
            // lib.js decryptFile takes (encryptedBuffer, rawKey, iv, type)
            // encryptFile returns encryptedBlob.
            // Fallback for reading blob
            const encryptedBuffer = await new Promise((resolve, reject) => {
                const reader = new FileReader();
                reader.onload = () => resolve(reader.result);
                reader.onerror = reject;
                reader.readAsArrayBuffer(encryptedBlob);
            });

            const decryptedBlob = await decryptFile(encryptedBuffer, receivedKey, receivedIv, receivedPayload.type);
            // Fallback for reading decrypted blob
            const decryptedBuffer = await new Promise((resolve, reject) => {
                const reader = new FileReader();
                reader.onload = () => resolve(reader.result);
                reader.onerror = reject;
                reader.readAsArrayBuffer(decryptedBlob);
            });
            const decryptedBytes = new Uint8Array(decryptedBuffer);

            expect(decryptedBytes).toEqual(fileCheck);
        })

        it('the government can decrypt a whole conversation', async function () {
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const aliceCertificate = await alice.generateCertificate('alice')
            const bobCertificate = await bob.generateCertificate('bob')
            const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))
            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await bob.receiveCertificate(aliceCertificate, aliceCertSignature)

            const msgs = ['Msg 1', 'Msg 2', 'Msg 3'];
            const cts = [];

            for (const msg of msgs) {
                cts.push(await alice.sendMessage('bob', msg));
                // Bob receives to advance ratchet
                await bob.receiveMessage('alice', cts[cts.length - 1]);
            }

            for (let i = 0; i < msgs.length; i++) {
                const decrypted = await govDecrypt(govKeyPair.sec, cts[i]);
                expect(decrypted).toEqual(msgs[i]);
            }
        })


        // Remaining tests (streams, multiple parties, shuffling) are logic-based and should work fine 
        // without structural changes, just strict syntax updates if any.

        it('handles shuffled messages in single stream', async function () {
            // ... same logic
            const alice = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const bob = new MessengerClient(caKeyPair.pub, govKeyPair.pub)
            const aliceCertificate = await alice.generateCertificate('alice')
            const aliceCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(aliceCertificate))
            const bobCertificate = await bob.generateCertificate('bob')
            const bobCertSignature = await signWithECDSA(caKeyPair.sec, stringifyCert(bobCertificate))

            await alice.receiveCertificate(bobCertificate, bobCertSignature)
            await bob.receiveCertificate(aliceCertificate, aliceCertSignature)

            const message1 = 'message 1'
            const ct1 = await alice.sendMessage('bob', message1)
            const message2 = 'message 2'
            const ct2 = await alice.sendMessage('bob', message2)
            const message3 = 'message 3'
            const ct3 = await alice.sendMessage('bob', message3)

            let result = await bob.receiveMessage('alice', ct1)
            expect(result).toEqual(message1)
            result = await bob.receiveMessage('alice', ct3)
            expect(result).toEqual(message3)
            result = await bob.receiveMessage('alice', ct2)
            expect(result).toEqual(message2)
        })
    })
})
